name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      mm-version:
        description: 'Mattermost version'
        type: string
        default: "9.4.1"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "wmluke/main-cloud-builder"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          tags: wmluke/mattermost:latest,wmluke/mattermost:${{ inputs.mm-version }}
          build-args: MM_VERSION=${{ inputs.mm-version }}
          outputs: 'type=registry,push=true'
